package com.awifi.core.atomic.dbc.device.manage.entity;

import java.util.Date;

public class CenterPubDeviceUpgradeRegion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_pub_device_upgrade_region.id
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_pub_device_upgrade_region.corporation_id
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    private Long corporationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_pub_device_upgrade_region.model_id
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    private Long modelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_pub_device_upgrade_region.versions
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    private String versions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_pub_device_upgrade_region.hd_versions
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    private String hdVersions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_pub_device_upgrade_region.type
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_pub_device_upgrade_region.path
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_pub_device_upgrade_region.province
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    private Integer province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_pub_device_upgrade_region.city
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    private Integer city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_pub_device_upgrade_region.county
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    private Integer county;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_pub_device_upgrade_region.issue_num
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    private Long issueNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_pub_device_upgrade_region.success_num
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    private Long successNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_pub_device_upgrade_region.start_time
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_pub_device_upgrade_region.status
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_pub_device_upgrade_region.user_id
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_pub_device_upgrade_region.create_time
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_pub_device_upgrade_region.modify_time
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column center_pub_device_upgrade_region.state
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_pub_device_upgrade_region.id
     *
     * @return the value of center_pub_device_upgrade_region.id
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_pub_device_upgrade_region.id
     *
     * @param id the value for center_pub_device_upgrade_region.id
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_pub_device_upgrade_region.corporation_id
     *
     * @return the value of center_pub_device_upgrade_region.corporation_id
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    public Long getCorporationId() {
        return corporationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_pub_device_upgrade_region.corporation_id
     *
     * @param corporationId the value for center_pub_device_upgrade_region.corporation_id
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    public void setCorporationId(Long corporationId) {
        this.corporationId = corporationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_pub_device_upgrade_region.model_id
     *
     * @return the value of center_pub_device_upgrade_region.model_id
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    public Long getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_pub_device_upgrade_region.model_id
     *
     * @param modelId the value for center_pub_device_upgrade_region.model_id
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    public void setModelId(Long modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_pub_device_upgrade_region.versions
     *
     * @return the value of center_pub_device_upgrade_region.versions
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    public String getVersions() {
        return versions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_pub_device_upgrade_region.versions
     *
     * @param versions the value for center_pub_device_upgrade_region.versions
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    public void setVersions(String versions) {
        this.versions = versions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_pub_device_upgrade_region.hd_versions
     *
     * @return the value of center_pub_device_upgrade_region.hd_versions
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    public String getHdVersions() {
        return hdVersions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_pub_device_upgrade_region.hd_versions
     *
     * @param hdVersions the value for center_pub_device_upgrade_region.hd_versions
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    public void setHdVersions(String hdVersions) {
        this.hdVersions = hdVersions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_pub_device_upgrade_region.type
     *
     * @return the value of center_pub_device_upgrade_region.type
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_pub_device_upgrade_region.type
     *
     * @param type the value for center_pub_device_upgrade_region.type
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_pub_device_upgrade_region.path
     *
     * @return the value of center_pub_device_upgrade_region.path
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_pub_device_upgrade_region.path
     *
     * @param path the value for center_pub_device_upgrade_region.path
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_pub_device_upgrade_region.province
     *
     * @return the value of center_pub_device_upgrade_region.province
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    public Integer getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_pub_device_upgrade_region.province
     *
     * @param province the value for center_pub_device_upgrade_region.province
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    public void setProvince(Integer province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_pub_device_upgrade_region.city
     *
     * @return the value of center_pub_device_upgrade_region.city
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    public Integer getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_pub_device_upgrade_region.city
     *
     * @param city the value for center_pub_device_upgrade_region.city
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    public void setCity(Integer city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_pub_device_upgrade_region.county
     *
     * @return the value of center_pub_device_upgrade_region.county
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    public Integer getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_pub_device_upgrade_region.county
     *
     * @param county the value for center_pub_device_upgrade_region.county
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    public void setCounty(Integer county) {
        this.county = county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_pub_device_upgrade_region.issue_num
     *
     * @return the value of center_pub_device_upgrade_region.issue_num
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    public Long getIssueNum() {
        return issueNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_pub_device_upgrade_region.issue_num
     *
     * @param issueNum the value for center_pub_device_upgrade_region.issue_num
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    public void setIssueNum(Long issueNum) {
        this.issueNum = issueNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_pub_device_upgrade_region.success_num
     *
     * @return the value of center_pub_device_upgrade_region.success_num
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    public Long getSuccessNum() {
        return successNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_pub_device_upgrade_region.success_num
     *
     * @param successNum the value for center_pub_device_upgrade_region.success_num
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    public void setSuccessNum(Long successNum) {
        this.successNum = successNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_pub_device_upgrade_region.start_time
     *
     * @return the value of center_pub_device_upgrade_region.start_time
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_pub_device_upgrade_region.start_time
     *
     * @param startTime the value for center_pub_device_upgrade_region.start_time
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_pub_device_upgrade_region.status
     *
     * @return the value of center_pub_device_upgrade_region.status
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_pub_device_upgrade_region.status
     *
     * @param status the value for center_pub_device_upgrade_region.status
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_pub_device_upgrade_region.user_id
     *
     * @return the value of center_pub_device_upgrade_region.user_id
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_pub_device_upgrade_region.user_id
     *
     * @param userId the value for center_pub_device_upgrade_region.user_id
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_pub_device_upgrade_region.create_time
     *
     * @return the value of center_pub_device_upgrade_region.create_time
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_pub_device_upgrade_region.create_time
     *
     * @param createTime the value for center_pub_device_upgrade_region.create_time
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_pub_device_upgrade_region.modify_time
     *
     * @return the value of center_pub_device_upgrade_region.modify_time
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_pub_device_upgrade_region.modify_time
     *
     * @param modifyTime the value for center_pub_device_upgrade_region.modify_time
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column center_pub_device_upgrade_region.state
     *
     * @return the value of center_pub_device_upgrade_region.state
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column center_pub_device_upgrade_region.state
     *
     * @param state the value for center_pub_device_upgrade_region.state
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    public void setState(Integer state) {
        this.state = state;
    }
}