package com.awifi.core.atomic.dbc.device.manage.dao;

import com.awifi.core.atomic.dbc.device.manage.entity.CenterPubDeviceUpgradeRegion;
import com.awifi.core.atomic.dbc.device.manage.entity.CenterPubDeviceUpgradeRegionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CenterPubDeviceUpgradeRegionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_pub_device_upgrade_region
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    int countByExample(CenterPubDeviceUpgradeRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_pub_device_upgrade_region
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    int deleteByExample(CenterPubDeviceUpgradeRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_pub_device_upgrade_region
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_pub_device_upgrade_region
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    int insert(CenterPubDeviceUpgradeRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_pub_device_upgrade_region
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    int insertSelective(CenterPubDeviceUpgradeRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_pub_device_upgrade_region
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    List<CenterPubDeviceUpgradeRegion> selectByExample(CenterPubDeviceUpgradeRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_pub_device_upgrade_region
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    CenterPubDeviceUpgradeRegion selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_pub_device_upgrade_region
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    int updateByExampleSelective(@Param("record") CenterPubDeviceUpgradeRegion record, @Param("example") CenterPubDeviceUpgradeRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_pub_device_upgrade_region
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    int updateByExample(@Param("record") CenterPubDeviceUpgradeRegion record, @Param("example") CenterPubDeviceUpgradeRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_pub_device_upgrade_region
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    int updateByPrimaryKeySelective(CenterPubDeviceUpgradeRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table center_pub_device_upgrade_region
     *
     * @mbggenerated Tue Jul 11 10:30:32 CST 2017
     */
    int updateByPrimaryKey(CenterPubDeviceUpgradeRegion record);
}